# Generated by Django 6.0.5 on 2026-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('company', models.CharField(max_length=100, verbose_name='empresa')),
                ('description', models.TextField(verbose_name='descrição')),
                ('job_type', models.CharField(choices=[('estagio', 'Estágio'), ('aprendiz', 'Jovem Aprendiz'), ('primeiro_emprego', 'Primeiro Emprego')], max_length=20, verbose_name='tipo de vaga')),
                ('area', models.CharField(max_length=100, verbose_name='área de atuação')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(default='PR', max_length=2, verbose_name='estado')),
                ('external_link', models.URLField(verbose_name='link externo/candidatura')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20, verbose_name='origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'ordering': ['-created_at'],
            },
        ),
    ]
